version: '3.5'
services:

 ProductService:
  image: ${DOCKER_REGISTRY-}producstmicroservice:v1
  build:
   context: ./ProductService
   dockerfile: Dockerfile
  environment:
   - CONNECTIONSTRINGS__DEFAULTCONNECTION=Data Source=192.168.8.123,1433;Initial Catalog=ProductServiceDB;User Id=username;Password=Password@123
  ports:
   - "4201:80"
 UserService:
  image: ${DOCKER_REGISTRY-}usersmicroservice:v1
  build:
   context: ./UserService
   dockerfile: Dockerfile
  environment:
   - CONNECTIONSTRINGS__DEFAULTCONNECTION=Data Source=192.168.8.123,1433;Initial Catalog=UserServiceDB;User Id=username;Password=Password@123
  ports:
   - "4202:80"